# ---
# - hosts: localhost
#   tasks:
#     - fail:
#         msg: "[ERROR] Empty inventory. No host available."
#       when: groups.all|length == 0

- hosts: api
  remote_user: admin

  pre_tasks:
    - name: Update apt cache if needed.
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - admin
    - role: traefik
    - role: api
      vars:
        docker_tag: main
        env_file: production
        api_domain: safetynet-api-production.dump.hr
