---
- hosts: api
  remote_user: admin

  pre_tasks:
    - name: Update apt cache if needed.
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - admin
    - role: traefik
    - role: api
      vars:
        docker_image: traefik/whoami
