creation_rules:
  - path_regex: main\.enc
    age: >-
      age16gh46p9yaujce9hsrdd69j3yv3ef4rsp98x62sqh6xepyvfe2f2qd0l0hf,
      age1mmc0rf8n6km2a5mygd457czjw9uf5t4x58yfflkta346zpylkupsjzydpn

# gh-actions  6gh..0hf
# bartol      mmc..dpn
# duje        TODO
