---
collections:
  - name: community.general
    version: 7.2.0
  - name: community.docker
    version: 3.4.8
  - name: community.sops
    version: 1.6.4
  - name: ansible.posix
    version: 1.5.4
  - name: amazon.aws
    version: 6.2.0

roles:
  - name: geerlingguy.docker
    version: 6.1.0
