---
plugin: aws_ec2
profile: safetynet

regions:
  - eu-central-1

hostnames:
  - ip-address

filters:
  tag:Project: safetynet
  tag:Environment: preview

keyed_groups:
  - key: tags.Role
  - key: tags.Branch
    prefix: preview
leading_separator: false
