---
- name: Load Alloy secrets from SOPS
  set_fact:
    alloy_secrets: "{{ lookup('community.sops.sops', role_path + '/files/auth.env.enc') }}"

- name: Download Grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg-full.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0644'
  become: true

- name: Add Grafana apt repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main'
    filename: grafana
    state: present
  become: true

- name: Install Alloy package
  ansible.builtin.apt:
    name: alloy
    update_cache: yes
    state: present
  become: true

- name: Add alloy user to docker group
  ansible.builtin.user:
    name: alloy
    groups: docker
    append: yes
  become: true
  notify: Restart Alloy Service

- name: Deploy Alloy configuration file
  ansible.builtin.copy:
    src: '{{ role_path }}/files/config.alloy'
    dest: /etc/alloy/config.alloy
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Alloy Service

- name: Update the Environment file
  ansible.builtin.copy:
    dest: /etc/default/alloy
    content: |
      CONFIG_FILE="/etc/alloy/config.alloy"
      CUSTOM_ARGS="--storage.path=/var/lib/alloy/data"
      {{ alloy_secrets }}
    owner: root
    group: root
    mode: '0600'
  become: true
  notify: Restart Alloy Service

- name: Ensure Alloy is started and enabled
  ansible.builtin.systemd:
    name: alloy
    state: started
    enabled: true
  become: true
