---
- name: Create node-exporter docker container
  docker_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter:v1.12.1
    restart_policy: unless-stopped
    network_mode: host
    pid_mode: host
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
